services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      PHX_SERVER: 'true'
      PHX_HOST: ${PHX_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      POOL_SIZE: ${POOL_SIZE:-10}
      REDIS_URL: ${REDIS_URL:-redis}
      REDIS_USERNAME: ${REDIS_USERNAME:-}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      RABBIT_MQ_HOST: ${RABBIT_MQ_HOST:-shared-rabbitmq}
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT:-5672}
      RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      RABBIT_MQ_VHOST: ${RABBIT_MQ_VHOST:-/}
      GO_CHAMPS_API_URL: ${GO_CHAMPS_API_URL}
      DNS_CLUSTER_QUERY: ${DNS_CLUSTER_QUERY:-}
    healthcheck:
      test: ['CMD', 'wget', '--header=X-Forwarded-Proto: https', '--spider', '-q', 'http://localhost:4000/']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - coolify

networks:
  coolify:
    external: true
