import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :go_champs_scoreboard, GoChampsScoreboardWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

# DATABASE_URL and POOL_SIZE are set at runtime (config/runtime.exs), since
# they're read via System.get_env and must reflect the deploy environment,
# not whatever was set when the release was compiled.
config :go_champs_scoreboard, GoChampsScoreboard.Repo,
  ssl: true,
  ssl_opts: [verify: :verify_none]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: GoChampsScoreboard.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# CORS Configuration for Production
config :go_champs_scoreboard, GoChampsScoreboardWeb.Endpoint,
  cors: [
    origins: ~r/https:\/\/(.*\.)?go-champs\.com$/,
    allow_credentials: true,
    allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers: ["Authorization", "Content-Type", "Accept", "Origin", "User-Agent"],
    expose_headers: ["content-length", "x-request-id"],
    max_age: 86400
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
